ALTER TABLE public.seller_stores
  ADD COLUMN IF NOT EXISTS is_open boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS open_hours text,
  ADD COLUMN IF NOT EXISTS closed_note text;

CREATE TABLE IF NOT EXISTS public.seller_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number bigint GENERATED BY DEFAULT AS IDENTITY,
  store_id uuid NOT NULL REFERENCES public.seller_stores(id) ON DELETE CASCADE,
  product_id uuid,
  seller_visitor_id text,
  buyer_visitor_id text NOT NULL,
  product_title text NOT NULL,
  variant_name text,
  qty integer NOT NULL DEFAULT 1,
  price bigint NOT NULL DEFAULT 0,
  total bigint NOT NULL DEFAULT 0,
  buyer_name text,
  buyer_phone text,
  buyer_address text,
  buyer_note text,
  status text NOT NULL DEFAULT 'pending',
  courier text,
  tracking_number text,
  shipping_note text,
  shipped_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seller_orders TO anon, authenticated;
GRANT ALL ON public.seller_orders TO service_role;
ALTER TABLE public.seller_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read seller orders" ON public.seller_orders FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Anyone can create seller order" ON public.seller_orders FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Anyone can update seller order" ON public.seller_orders FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Anyone can delete seller order" ON public.seller_orders FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS public.seller_order_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.seller_orders(id) ON DELETE CASCADE,
  sender text NOT NULL DEFAULT 'buyer',
  visitor_id text,
  message text NOT NULL,
  image_url text,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seller_order_messages TO anon, authenticated;
GRANT ALL ON public.seller_order_messages TO service_role;
ALTER TABLE public.seller_order_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read seller order messages" ON public.seller_order_messages FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Anyone can send seller order message" ON public.seller_order_messages FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Anyone can update seller order message" ON public.seller_order_messages FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.seller_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_number bigint GENERATED BY DEFAULT AS IDENTITY,
  product_id uuid,
  order_id uuid,
  store_id uuid,
  visitor_id text NOT NULL,
  reason text NOT NULL,
  detail text,
  status text NOT NULL DEFAULT 'pending',
  admin_note text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seller_reports TO anon, authenticated;
GRANT ALL ON public.seller_reports TO service_role;
ALTER TABLE public.seller_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read seller reports" ON public.seller_reports FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Anyone can create seller report" ON public.seller_reports FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Anyone can update seller report" ON public.seller_reports FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.seller_earnings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES public.seller_stores(id) ON DELETE CASCADE,
  order_id uuid,
  gross bigint NOT NULL DEFAULT 0,
  fee bigint NOT NULL DEFAULT 0,
  net bigint NOT NULL DEFAULT 0,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seller_earnings TO anon, authenticated;
GRANT ALL ON public.seller_earnings TO service_role;
ALTER TABLE public.seller_earnings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read seller earnings" ON public.seller_earnings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Anyone can create seller earning" ON public.seller_earnings FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_seller_orders_store ON public.seller_orders(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_seller_orders_buyer ON public.seller_orders(buyer_visitor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_seller_order_msg ON public.seller_order_messages(order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_seller_earnings_store ON public.seller_earnings(store_id, created_at DESC);